### ISSUE TITLE
Broken configuration parsing of rules

### ISSUE THREAD

**Issue by kalaksi** [ananace/ruby-grafana-matrix#13]
Seems that configuration parsing of rules is broken and results in empty list of rules. I'm using docker (so ruby 2.6) to run this project. In practice this means that the server always responds 404 even for valid requests.

I found that the commit that breaks this is 23c82f9d04805b43d1ec13f163fe71b338e66559.

This fixes the issue:
```
--- a/lib/grafana_matrix/config.rb
+++ b/lib/grafana_matrix/config.rb
@@ -113,7 +113,7 @@ module GrafanaMatrix
         client_data = client_data.dup
 
         # Symbolize keys
-        client_data.each_key do |key|
+        client_data.keys.each do |key|
           client_data[(key.to_sym rescue key)] = client_data.delete key
         end
 
@@ -129,7 +129,7 @@ module GrafanaMatrix
         rule_data = rule_data.dup
 
         # Symbolize keys
-        rule_data.each_key do |key|
+        rule_data.keys.each do |key|
           rule_data[(key.to_sym rescue key)] = rule_data.delete key
         end
```

**Comment by kalaksi** [comment]
Also, it was difficult to find working versions in the commit history. Tagging commits that should work would help.

**Comment by ananace** [comment]
Yeah, never started tagging up image information as it's all been manually built and pushed. I'll have a look at cleaning up the code a bit and tagging up a proper release soon.
