### ISSUE TITLE
config.yml.example claims to accept `room or ID`, but will crash if not given an ID

### ISSUE THREAD

**Issue by jeffcasavant** [ananace/ruby-grafana-matrix#2]
Config:
```
room: "#ops:casavant.org"
```
Error:

```
2018-09-01 11:45:15 - MatrixSdk::MatrixRequestError - Expected RoomID string to start with '!':
```

**Comment by jeffcasavant** [comment]
I build my environment for ruby-grafana-matrix using rbenv + bundler - it's the latest code from this repo plus whatever versions of support libraries are specified in it.

**Comment by ananace** [comment]
Could you give me the full backtrace of the error in that case?

It really shouldn't have any issues with accepting room aliases, as that's what I developed it with and what I'm using it with myself.

**Comment by jeffcasavant** [comment]
https://gist.github.com/jeffcasavant/7d0ebd2021ef4dafc8b8f15c1d38a2d6 - you can see the error in question is about halfway down.  I think the first half has to do with image upload failing.

**Comment by ananace** [comment]
Found the issue, and it's only with newer SDK than the one my running version is on, should be fixed now.
